In [2]:
import pandas as pd
# First DataFrame
df1 = pd.DataFrame({'id': ['A01', 'A02', 'A03', 'A04'],
					'Name': ['ABC', 'PQR', 'DEF', 'GHI']})
display(df1)
# Second DataFrame
df2 = pd.DataFrame({'id': ['B05', 'B06', 'B07', 'B08','B09'],
					'Name': ['XYZ', 'TUV', 'MNO', 'JKL','GHI']})
display(df2)

frames = [df1, df2]

result = pd.concat(frames)
#result = pd.concat(frames,axis=1)
display(result)
result.reset_index(inplace=True,drop=True)
display(result)

    id Name
0  A01  ABC
1  A02  PQR
2  A03  DEF
3  A04  GHI

    id Name
0  B05  XYZ
1  B06  TUV
2  B07  MNO
3  B08  JKL
4  B09  GHI

    id Name
0  A01  ABC
1  A02  PQR
2  A03  DEF
3  A04  GHI
0  B05  XYZ
1  B06  TUV
2  B07  MNO
3  B08  JKL
4  B09  GHI

    id Name
0  A01  ABC
1  A02  PQR
2  A03  DEF
3  A04  GHI
4  B05  XYZ
5  B06  TUV
6  B07  MNO
7  B08  JKL
8  B09  GHI