In [3]:
from IPython.core.display_functions import display
import pandas as pd

#Create Series
s = pd.Series([3, 4, 5], ['earth', 'mars', 'jupiter'])
k = pd.Series([1, 2, 3], ['earth', 'mars', 'jupiter'])

#Create DataFrame df from two series
df = pd.DataFrame({'mass': s, 'diameter': k})

display(df)

#Assign df to variable_copy
variable_copy = df

display(variable_copy)
#Update the value of mass of earth in original dataframe
df['mass']['earth'] = 8

display(variable_copy)

res = df.copy(deep=True)
display(res)

         mass  diameter
earth       3         1
mars        4         2
jupiter     5         3

         mass  diameter
earth       3         1
mars        4         2
jupiter     5         3

         mass  diameter
earth       8         1
mars        4         2
jupiter     5         3

         mass  diameter
earth       8         1
mars        4         2
jupiter     5         3