In [12]:
from IPython.core.display_functions import display
# Import pandas package
import pandas as pd

# create a dictionary with five fields each
data = {
    'A': ['A1', 'A2', 'A3', 'A4', 'A5'],
    'B': ['B1', 'B2', 'B3', 'B4', 'B5'],
    'C': ['C1', 'C2', 'C3', 'C4', 'C5'],
    'D': ['D1', 'D2', 'D3', 'D4', 'D5'],
    'E': ['E1', 'E2', 'E3', 'E4', 'E5']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
display(df)

# Remove column name 'A'
#df1=df.drop(['A'], axis=1)
#display(df1)

# Remove two columns name is 'C' and 'D'
#df2=df.drop(['C', 'D'], axis=1)
#display(df2)

# Remove three columns as index base
#df3=df.drop(df.columns[[0, 4, 2]], axis=1, inplace=True)
#display(df3)

# Remove all columns between column index 1 to 3
#df4=df.drop(df.iloc[:, 1:3], inplace=True, axis=1)
#display(df4)

# Remove all columns between column name 'B' to 'D'
#df5=df.drop(df.ix[:, 'B':'D'].columns, axis=1)
#display(df5)

# Remove all columns between column name 'B' to 'D'
#df6=df.drop(df.loc[:, 'B':'D'].columns, axis=1)
#display(df6)

#Drop Columns from a Dataframe in an iterative way.
# for col in df.columns:
#     if 'A' in col:
#         del df[col]
# display(df)

#drop column using dataframe.pop() method
# df7=df.pop('B')
# display(df7)

#delete alternate rows
#df8=df.iloc[::2]
#df8.reset_index(drop=True,inplace=True)
#display(df8)

    A   B   C   D   E
0  A1  B1  C1  D1  E1
1  A2  B2  C2  D2  E2
2  A3  B3  C3  D3  E3
3  A4  B4  C4  D4  E4
4  A5  B5  C5  D5  E5

    A   B   C   D   E
0  A1  B1  C1  D1  E1
1  A3  B3  C3  D3  E3
2  A5  B5  C5  D5  E5