In [2]:
from IPython.core.display_functions import display
import pandas as pd

# Creating dataframe
df1 = pd.DataFrame([["rumul", 10, 12, 10],
                    ["rahul", 10, 11, 16],
                    ["purvi", 18, 14, 10],
                    ["ravi", 20, 13, 30]],
                   columns=["Name1", "Maths",
                            "Physics",
                            "Chemistry"])

# setting name1 as index column
df1 = df1.set_index('Name1')

display(df1)

# Creating another dataframe for
# replacement
df2 = pd.DataFrame(
    [["rahul", 1, 1]],
    columns=["Name2", "Maths", "Physics"])

df3 = pd.DataFrame(
    [["purvi", 5, 8]],
    columns=["Name3", "Maths", "Chemistry"])

# setting name2 and name3 as
# index column
df2 = df2.set_index('Name2')
df3 = df3.set_index('Name3')

# update the values at the
# passed index
df1.update(df2)
df1.update(df3)

display(df1)

       Maths  Physics  Chemistry
Name1
rumul     10       12         10
rahul     10       11         16
purvi     18       14         10
ravi      20       13         30

       Maths  Physics  Chemistry
Name1
rumul   10.0     12.0       10.0
rahul    1.0      1.0       16.0
purvi    5.0     14.0        8.0
ravi    20.0     13.0       30.0